# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cutw <- function() {
    .Call('rjieba_cutw', PACKAGE = 'rjieba')
}

#' @export
rcpp_hello_world <- function() {
    .Call('rjieba_rcpp_hello_world', PACKAGE = 'rjieba')
}

#' @export
timesTwo <- function(x) {
    .Call('rjieba_timesTwo', PACKAGE = 'rjieba', x)
}

